name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: Semana1/Actividad1/devops-practice
    
    - name: Check Docker and Docker Compose versions
      run: |
        docker --version
        docker compose version 

    - name: Build and run Docker Compose
      run: |
        docker compose up --build -d
      working-directory: Semana1/Actividad1/devops-practice

    - name: Run tests
      run: docker exec devop-practice-container npm test
    
    - name: Run Docker container
      run: |
        docker compose down
      working-directory: Semana1/Actividad1/devops-practice
